slice_name: Avg delivery time
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: big_number_total
  metric: avg_delivery_time
  granularity_sqla: sent_date
  subheader: ms
query_context: null
cache_timeout: null
uuid: 0ace3b5b-7e1b-4643-88dc-ec733b09240f
version: 1.0.0
dataset_uuid: 64857edb-ff1a-4d43-9739-a514bdaefa63
