slice_name: Avg delivery time
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: big_number_total
  metric: avg_delivery_time
  granularity_sqla: sent_date
  subheader: ms
query_context: null
cache_timeout: null
uuid: c412411e-b484-4c75-9700-f9f8879a943f
version: 1.0.0
dataset_uuid: 77a9edc1-b029-4d52-b0b3-6db544b36fc1
