slice_name: Avg delivery time by operator
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 1__table
  row_limit: 10
  adhoc_filters: []
  viz_type: dist_bar
  metrics:
  - avg_delivery_time
  groupby:
  - receiver_operator
  order_desc: true
  granularity_sqla: sent_date
query_context: null
cache_timeout: null
uuid: bbdeded7-7f76-45a4-8cb4-bd682fa1fe02
version: 1.0.0
dataset_uuid: 77a9edc1-b029-4d52-b0b3-6db544b36fc1
