slice_name: Cohort retention
description: null
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 2__table
  viz_type: heatmap_v2
  x_axis: month_index
  groupby: cohort_month
  metric: retention_pct_max
  row_limit: 10000
  adhoc_filters:
  - expressionType: SIMPLE
    subject: month_index
    operator: '>'
    comparator: '0'
    clause: WHERE
  sort_x_axis: value_asc
  sort_y_axis: value_asc
  normalize_across: y
  legend_type: continuous
  linear_color_scheme: dark_blue
  show_values: true
  value_bounds:
  - 0
  - 100
  y_axis_format: SMART_NUMBER
query_context: null
cache_timeout: null
uuid: ae4b9413-fe25-4c0c-9d86-55d68a5b5a6a
version: 1.0.0
dataset_uuid: 579c5642-5b68-47a9-b3c7-77f46d005820
