slice_name: Delivery rate by country
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 1__table
  row_limit: 10
  adhoc_filters: []
  viz_type: dist_bar
  metrics:
  - delivery_rate_pct
  groupby:
  - country
  order_desc: true
  granularity_sqla: sent_date
query_context: null
cache_timeout: null
uuid: 38e7f799-7606-4618-bf40-68022a106db8
version: 1.0.0
dataset_uuid: 74b5cfb1-c383-415e-86d4-65caeb20c02c
