slice_name: Delivery rate
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: big_number_total
  metric: delivery_rate_pct
  granularity_sqla: sent_date
  subheader: '% delivered (DELIVRD)'
query_context: null
cache_timeout: null
uuid: a38638b2-e69e-4aa7-979c-b0a55af5e5a9
version: 1.0.0
dataset_uuid: 74b5cfb1-c383-415e-86d4-65caeb20c02c
