slice_name: Failed rate
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: big_number_total
  metric: failed_rate_pct
  granularity_sqla: sent_date
  subheader: '% not delivered'
query_context: null
cache_timeout: null
uuid: b00108f2-7526-4836-93df-8b62b5d88315
version: 1.0.0
dataset_uuid: 64857edb-ff1a-4d43-9739-a514bdaefa63
