slice_name: Failed statuses
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 1__table
  row_limit: 10
  adhoc_filters:
  - expressionType: SIMPLE
    subject: delivery_status
    operator: NOT IN
    comparator:
    - DELIVRD
    clause: WHERE
  viz_type: dist_bar
  metrics:
  - count_messages
  groupby:
  - delivery_status
  order_desc: true
  granularity_sqla: sent_date
query_context: null
cache_timeout: null
uuid: 27aa975a-cdf0-4657-86c0-b521ac33aafc
version: 1.0.0
dataset_uuid: 77a9edc1-b029-4d52-b0b3-6db544b36fc1
