slice_name: Failed statuses
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 1__table
  row_limit: 10
  adhoc_filters:
  - expressionType: SIMPLE
    subject: delivery_status
    operator: NOT IN
    comparator:
    - DELIVRD
    clause: WHERE
  viz_type: dist_bar
  metrics:
  - count_messages
  groupby:
  - delivery_status
  order_desc: true
  granularity_sqla: sent_date
query_context: null
cache_timeout: null
uuid: 03d5fb3c-d802-4b1a-b5bb-dbac62a87431
version: 1.0.0
dataset_uuid: 74b5cfb1-c383-415e-86d4-65caeb20c02c
