slice_name: Failed rate
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: big_number_total
  metric: failed_rate_pct
  granularity_sqla: sent_date
  subheader: '% not delivered'
query_context: null
cache_timeout: null
uuid: 1b55cdaa-5361-43c3-8935-af43ca896624
version: 1.0.0
dataset_uuid: 74b5cfb1-c383-415e-86d4-65caeb20c02c
