slice_name: Revenue by currency
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: dist_bar
  metrics:
  - revenue
  groupby:
  - currency
  order_desc: true
  granularity_sqla: sent_date
query_context: null
cache_timeout: null
uuid: 1754ed34-c636-450d-8eab-897eff0ee80f
version: 1.0.0
dataset_uuid: 74b5cfb1-c383-415e-86d4-65caeb20c02c
