slice_name: Revenue (total)
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: big_number_total
  metric: revenue
  granularity_sqla: sent_date
  subheader: sum(price), mixed currency
query_context: null
cache_timeout: null
uuid: e7c8f2c0-fc78-4d39-a093-4c89ececdf2a
version: 1.0.0
dataset_uuid: 64857edb-ff1a-4d43-9739-a514bdaefa63
