slice_name: Revenue (total)
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 1__table
  row_limit: 10000
  adhoc_filters: []
  viz_type: big_number_total
  metric: revenue
  granularity_sqla: sent_date
  subheader: sum(price), mixed currency
query_context: null
cache_timeout: null
uuid: 4a1a648f-e360-4c70-bb37-15169fb11c05
version: 1.0.0
dataset_uuid: 74b5cfb1-c383-415e-86d4-65caeb20c02c
