slice_name: Top operators
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 1__table
  row_limit: 10
  adhoc_filters: []
  viz_type: pie
  metric: count_messages
  groupby:
  - receiver_operator
  granularity_sqla: sent_date
query_context: null
cache_timeout: null
uuid: 5bb62eaa-191c-45b4-b851-6b2b92f583fd
version: 1.0.0
dataset_uuid: 64857edb-ff1a-4d43-9739-a514bdaefa63
