slice_name: Top countries
description: null
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  datasource: 1__table
  row_limit: 10
  adhoc_filters: []
  viz_type: dist_bar
  metrics:
  - count_messages
  groupby:
  - country
  order_desc: true
  granularity_sqla: sent_date
query_context: null
cache_timeout: null
uuid: 5f1977b1-8c5b-492b-adae-b0dc14861f90
version: 1.0.0
dataset_uuid: 74b5cfb1-c383-415e-86d4-65caeb20c02c
